using System.Linq;
using NUnit.Framework;

namespace Zeta.Extreme.Form.Tests.ZC371TestBench {
	[TestFixture]

	public class Zc371TestBench {
		[TestCase("A|B|C", "A", true, true)]
		[TestCase("A|B|C", "B", true, true)]
		[TestCase("A|B|C", "C", true, true)]
		[TestCase("A|B|C", "C,B", true, true)]
		[TestCase("A,B,C", "C,B", false, true)]
		[TestCase("A,B,C", "C,B,A", true, true)]
		[TestCase("A,B|C", "C", true, true)]
		[TestCase("A,B|C", "A,B", true, true)]
		[TestCase("A,B|C", "B", false, true)]
		[TestCase("A|B|C", "", false, true)]
		[TestCase("A,B,C", "D", false, true)]

		[TestCase("A|B|C", "A", true, false)]
		[TestCase("A|B|C", "B", true, false)]
		[TestCase("A|B|C", "C", true, false)]
		[TestCase("A|B|C", "C,B", true, false)]
		[TestCase("A,B,C", "C,B", false, false)]
		[TestCase("A,B,C", "C,B,A", true, false)]
		[TestCase("A,B|C", "C", true, false)]
		[TestCase("A,B|C", "A,B", true, false)]
		[TestCase("A,B|C", "B", false, false)]
		[TestCase("A|B|C", "", false, false)]
		[TestCase("A,B,C", "D", false,false)]
		public void AllMatchersWorkOnListValid(string condition, string conditions, bool value,bool usenew) {
			PerformSingleConditionTest(condition, conditions, value, usenew);
		}

		private static void PerformSingleConditionTest(string condition, string conditions, bool value, bool usenew) {
			var matcher = usenew
				              ? (ConditionMatcherBase) new NewConditionMatcherImplementation()
				              : new OldConditionMatcherImplementation();
			var result = matcher.Match(condition, conditions.Split(','));
			Assert.AreEqual(value, result, "old matcher problem");
			Assert.AreEqual(0, matcher.EvaluatedByScriptCount, "old matcher script");
		}


		[TestCase("A and B","A",false)]
		[TestCase("A and B", "B", false)]
		[TestCase("A and B", "A,B", true)]
		[TestCase("A and (B or C) and not D", "A", false)]
		[TestCase("A and (B or C) and not D", "A,B", true)]
		[TestCase("A and (B or C) and not D", "A,C", true)]
		[TestCase("A and (B or C) and not D", "B", false)]
		[TestCase("A and (B or C) and not D", "C", false)]
		[TestCase("A and (B or C) and not D", "B,C", false)]
		[TestCase("A and (B or C) and not D", "A,B,C", true)]
		[TestCase("A and (B or C) and not D", "A,B,C,D", false)]
		public void OldMatcherCanEvalFormulas (string condition, string conditions, bool value) {
			PerformSingleConditionTest(condition, conditions, value, false);
		}
		[TestCase("A and B", "A", false)]
		[TestCase("A and B", "B", false)]
		[TestCase("A and B", "A,B", true)]
		[TestCase("A and (B or C) and not D", "A", false)]
		[TestCase("A and (B or C) and not D", "A,B", true)]
		[TestCase("A and (B or C) and not D", "A,C", true)]
		[TestCase("A and (B or C) and not D", "B", false)]
		[TestCase("A and (B or C) and not D", "C", false)]
		[TestCase("A and (B or C) and not D", "B,C", false)]
		[TestCase("A and (B or C) and not D", "A,B,C", true)]
		[TestCase("A and (B or C) and not D", "A,B,C,D", false)]
		public void NewMatcherCanEvalFormulas(string condition, string conditions, bool value)
		{
			PerformSingleConditionTest(condition, conditions, value, true);
		}


		[TestCase("FACT and Y10", "FACT,Y10")]
		[TestCase("FACT and Y9", "FACT,Y9")]
		[TestCase("FACT and Y8", "FACT,Y8")]
		[TestCase("FACT and Y7", "FACT,Y7")]
		[TestCase("FACT and Y6", "FACT,Y6")]
		[TestCase("FACT and Y5", "FACT,Y5")]
		[TestCase("FACT and Y4", "FACT,Y4")]
		[TestCase("FACT and Y3", "FACT,Y3")]
		[TestCase("FACT and Y2", "FACT,Y2")]
		[TestCase("FACT and Y1", "FACT,Y1")]
		[TestCase("FACT and Y2 and OTKL", "FACT,Y2,OTKL")]
		[TestCase("PRED and FACT and M12 ", "PRED,FACT,M12")]
		[TestCase("PRED and FACT and M11 ", "PRED,FACT,M11")]
		[TestCase("PRED and FACT and M10 ", "PRED,FACT,M10")]
		[TestCase("PRED and FACT and M9 ", "PRED,FACT,M9")]
		[TestCase("PRED and FACT and M8 ", "PRED,FACT,M8")]
		[TestCase("PRED and FACT and M7 ", "PRED,FACT,M7")]
		[TestCase("PRED and FACT and M6 ", "PRED,FACT,M6")]
		[TestCase("PRED and FACT and M5 ", "PRED,FACT,M5")]
		[TestCase("PRED and FACT and M4 ", "PRED,FACT,M4")]
		[TestCase("PRED and FACT and M3 ", "PRED,FACT,M3")]
		[TestCase("PRED and FACT and M2 ", "PRED,FACT,M2")]
		[TestCase("PRED and FACT", "PRED,FACT")]
		[TestCase("FACT and BYMONTH", "FACT,BYMONTH")]
		[TestCase("PRED and M1 and FACT and BYMONTH and OTKL", "PRED,M1,FACT,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and BYMONTH and OTKL", "PLAN,FACT,BYMONTH,OTKL")]
		[TestCase("PREDYEAR and FACT", "PREDYEAR,FACT")]
		[TestCase("PLAN and СНГ and not KVKURS", "PLAN,СНГ,KVKURS")]
		[TestCase("FACT and СНГ", "FACT,СНГ")]
		[TestCase("FACT and СНГ and OTKL and PREDYEAR", "FACT,СНГ,OTKL,PREDYEAR")]
		[TestCase(" OZHID and OTKL ", "OZHID,OTKL")]
		[TestCase("PLAN and FACT and СНГ and OTKL and not KVKURS", "PLAN,FACT,СНГ,OTKL,KVKURS")]
		[TestCase("PLAN and FACT and СНГ and OTKL and KVKURS", "PLAN,FACT,СНГ,OTKL,KVKURS")]
		[TestCase("FACT, PREDYEAR", "FACT,PREDYEAR")]
		[TestCase("PLAN, OTKL", "PLAN,OTKL")]
		[TestCase("not KVKURS and PLAN", "KVKURS,PLAN")]
		[TestCase("FACT and OTKL and PREDYEAR", "FACT,OTKL,PREDYEAR")]
		[TestCase("FACT and PLAN and OTKL", "FACT,PLAN,OTKL")]
		[TestCase("OTKL and PREDYEAR and OTKLABS ", "OTKL,PREDYEAR,OTKLABS")]
		[TestCase("OTKL and PLAN and OTKLABS ", "OTKL,PLAN,OTKLABS")]
		[TestCase("OTKL and PREDYEAR and OTKLOTN ", "OTKL,PREDYEAR,OTKLOTN")]
		[TestCase("OTKL and PLAN and OTKLOTN ", "OTKL,PLAN,OTKLOTN")]
		[TestCase("( FACT or OZHID )", "FACT,OZHID")]
		[TestCase("USETPFP and СНГ", "USETPFP,СНГ")]
		[TestCase("USETPFP and BYMONTH", "USETPFP,BYMONTH")]
		[TestCase("PLAN and СНГ", "PLAN,СНГ")]
		[TestCase("PLAN and BYMONTH", "PLAN,BYMONTH")]
		[TestCase("PLAN and KVART", "PLAN,KVART")]
		[TestCase("FACT and ( СНГ or KVART) ", "FACT,СНГ,KVART")]
		[TestCase("FACT and KVART", "FACT,KVART")]
		[TestCase("( FACT or OZHID ) and СНГ", "FACT,OZHID,СНГ")]
		[TestCase("( FACT or OZHID ) and BYMONTH", "FACT,OZHID,BYMONTH")]
		[TestCase("( FACT or OZHID ) and KVART", "FACT,OZHID,KVART")]
		[TestCase("PLAN and Y1", "PLAN,Y1")]
		[TestCase("FACT or OZHID", "FACT,OZHID")]
		[TestCase("not CONS and OZHID", "CONS,OZHID")]
		[TestCase("( BYMONTH  or СНГ ) and not CONS ", "BYMONTH,СНГ,CONS")]
		[TestCase("BYMONTH and not CONS", "BYMONTH,CONS")]
		[TestCase("СНГ and not CONS", "СНГ,CONS")]
		[TestCase("CONS and OZHID", "CONS,OZHID")]
		[TestCase("( BYMONTH  or СНГ ) and CONS ", "BYMONTH,СНГ,CONS")]
		[TestCase("BYMONTH and CONS", "BYMONTH,CONS")]
		[TestCase("СНГ and CONS", "СНГ,CONS")]
		[TestCase(" PRED and PM2 ", "PRED,PM2")]
		[TestCase(" PRED and PM3 ", "PRED,PM3")]
		[TestCase(" PRED and PM4 ", "PRED,PM4")]
		[TestCase(" PRED and PM5 ", "PRED,PM5")]
		[TestCase(" PRED and PM6 ", "PRED,PM6")]
		[TestCase(" PRED and PM7 ", "PRED,PM7")]
		[TestCase(" PRED and PM8 ", "PRED,PM8")]
		[TestCase(" PRED and PM9 ", "PRED,PM9")]
		[TestCase(" PRED and PM10 ", "PRED,PM10")]
		[TestCase(" PRED and PM11 ", "PRED,PM11")]
		[TestCase(" PRED and PM12 ", "PRED,PM12")]
		[TestCase("BYMONTH and not CONS and OTKL ", "BYMONTH,CONS,OTKL")]
		[TestCase("СНГ and not CONS and OTKL ", "СНГ,CONS,OTKL")]
		[TestCase("BYMONTH and CONS and OTKL ", "BYMONTH,CONS,OTKL")]
		[TestCase("СНГ and CONS and OTKL ", "СНГ,CONS,OTKL")]
		[TestCase("OPL and BYMONTH and VNOB", "OPL,BYMONTH,VNOB")]
		[TestCase("NACH and BYMONTH and VNOB", "NACH,BYMONTH,VNOB")]
		[TestCase("OST and СНГ", "OST,СНГ")]
		[TestCase("NACH and СНГ and VNOB", "NACH,СНГ,VNOB")]
		[TestCase("OPL and СНГ and VNOB", "OPL,СНГ,VNOB")]
		[TestCase("NACH and VNOB", "NACH,VNOB")]
		[TestCase("OPL and VNOB", "OPL,VNOB")]
		[TestCase("PRED and M12 ", "PRED,M12")]
		[TestCase("PRED and M11 ", "PRED,M11")]
		[TestCase("PRED and M10 ", "PRED,M10")]
		[TestCase("PRED and M9 ", "PRED,M9")]
		[TestCase("PRED and M8 ", "PRED,M8")]
		[TestCase("PRED and M7 ", "PRED,M7")]
		[TestCase("PRED and M6 ", "PRED,M6")]
		[TestCase("PRED and M5 ", "PRED,M5")]
		[TestCase("PRED and M4 ", "PRED,M4")]
		[TestCase("PRED and M3 ", "PRED,M3")]
		[TestCase("PRED and M2 ", "PRED,M2")]
		[TestCase("not CONS and ( BYMONTH  or СНГ ) ", "CONS,BYMONTH,СНГ")]
		[TestCase("CONS and ( BYMONTH  or СНГ ) ", "CONS,BYMONTH,СНГ")]
		[TestCase("OST and BYMONTH", "OST,BYMONTH")]
		[TestCase("NACH and BYMONTH", "NACH,BYMONTH")]
		[TestCase("OPL and BYMONTH", "OPL,BYMONTH")]
		[TestCase("OST and Y6 and PREDYEAR", "OST,Y6,PREDYEAR")]
		[TestCase("OST and Y5 and PREDYEAR", "OST,Y5,PREDYEAR")]
		[TestCase("OST and Y4 and PREDYEAR", "OST,Y4,PREDYEAR")]
		[TestCase("OST and Y3 and PREDYEAR", "OST,Y3,PREDYEAR")]
		[TestCase("OST and Y2 and PREDYEAR", "OST,Y2,PREDYEAR")]
		[TestCase("OST and Y1 and PREDYEAR", "OST,Y1,PREDYEAR")]
		[TestCase("NACH and СНГ", "NACH,СНГ")]
		[TestCase("OPL and СНГ", "OPL,СНГ")]
		[TestCase("PLAN and KOL and OSTN ", "PLAN,KOL,OSTN")]
		[TestCase("PLAN and CENA and OSTN ", "PLAN,CENA,OSTN")]
		[TestCase("PLAN and SUMMA and OSTN ", "PLAN,SUMMA,OSTN")]
		[TestCase("PLAN and KOL and PRIHOD ", "PLAN,KOL,PRIHOD")]
		[TestCase("PLAN and CENA and PRIHOD ", "PLAN,CENA,PRIHOD")]
		[TestCase("PLAN and SUMMA and PRIHOD", "PLAN,SUMMA,PRIHOD")]
		[TestCase("PLAN and KOL and RASHOD ", "PLAN,KOL,RASHOD")]
		[TestCase("PLAN and CENA and RASHOD ", "PLAN,CENA,RASHOD")]
		[TestCase("PLAN and SUMMA and RASHOD ", "PLAN,SUMMA,RASHOD")]
		[TestCase("PLAN and KOL and OSTK ", "PLAN,KOL,OSTK")]
		[TestCase("PLAN and CENA and OSTK ", "PLAN,CENA,OSTK")]
		[TestCase("PLAN and SUMMA and OSTK ", "PLAN,SUMMA,OSTK")]
		[TestCase("FACT and KOL and OSTN and BYMONTH", "FACT,KOL,OSTN,BYMONTH")]
		[TestCase("FACT and CENA and OSTN and BYMONTH", "FACT,CENA,OSTN,BYMONTH")]
		[TestCase("FACT and SUMMA and OSTN and BYMONTH", "FACT,SUMMA,OSTN,BYMONTH")]
		[TestCase("FACT and KOL and PRIHOD and BYMONTH", "FACT,KOL,PRIHOD,BYMONTH")]
		[TestCase("FACT and CENA and PRIHOD and BYMONTH", "FACT,CENA,PRIHOD,BYMONTH")]
		[TestCase("FACT and SUMMA and PRIHOD and BYMONTH", "FACT,SUMMA,PRIHOD,BYMONTH")]
		[TestCase("FACT and KOL and RASHOD and BYMONTH", "FACT,KOL,RASHOD,BYMONTH")]
		[TestCase("FACT and CENA and RASHOD and BYMONTH", "FACT,CENA,RASHOD,BYMONTH")]
		[TestCase("FACT and SUMMA and RASHOD and BYMONTH", "FACT,SUMMA,RASHOD,BYMONTH")]
		[TestCase("FACT and KOL and OSTK and BYMONTH", "FACT,KOL,OSTK,BYMONTH")]
		[TestCase("FACT and CENA and OSTK and BYMONTH", "FACT,CENA,OSTK,BYMONTH")]
		[TestCase("FACT and SUMMA and OSTK and BYMONTH", "FACT,SUMMA,OSTK,BYMONTH")]
		[TestCase("PRIHOD and BYMONTH", "PRIHOD,BYMONTH")]
		[TestCase("PLAN and FACT and KOL and PRIHOD and BYMONTH and OTKL", "PLAN,FACT,KOL,PRIHOD,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and CENA and PRIHOD and BYMONTH and OTKL", "PLAN,FACT,CENA,PRIHOD,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and PRIHOD and BYMONTH and OTKL", "PLAN,FACT,SUMMA,PRIHOD,BYMONTH,OTKL")]
		[TestCase("RASHOD and BYMONTH", "RASHOD,BYMONTH")]
		[TestCase("PLAN and FACT and SUMMA and RASHOD and BYMONTH and OTKL", "PLAN,FACT,SUMMA,RASHOD,BYMONTH,OTKL")]
		[TestCase("FACT and KOL and OSTN and СНГ", "FACT,KOL,OSTN,СНГ")]
		[TestCase("FACT and CENA and OSTN and СНГ", "FACT,CENA,OSTN,СНГ")]
		[TestCase("FACT and SUMMA and OSTN and СНГ", "FACT,SUMMA,OSTN,СНГ")]
		[TestCase("FACT and KOL and PRIHOD and СНГ", "FACT,KOL,PRIHOD,СНГ")]
		[TestCase("FACT and CENA and PRIHOD and СНГ", "FACT,CENA,PRIHOD,СНГ")]
		[TestCase("FACT and SUMMA and PRIHOD and СНГ", "FACT,SUMMA,PRIHOD,СНГ")]
		[TestCase("FACT and KOL and RASHOD and СНГ", "FACT,KOL,RASHOD,СНГ")]
		[TestCase("FACT and CENA and RASHOD and СНГ", "FACT,CENA,RASHOD,СНГ")]
		[TestCase("FACT and SUMMA and RASHOD and СНГ", "FACT,SUMMA,RASHOD,СНГ")]
		[TestCase("FACT and KOL and OSTK and СНГ", "FACT,KOL,OSTK,СНГ")]
		[TestCase("FACT and CENA and OSTK and СНГ", "FACT,CENA,OSTK,СНГ")]
		[TestCase("FACT and SUMMA and OSTK and СНГ", "FACT,SUMMA,OSTK,СНГ")]
		[TestCase("OST and PREDYEAR", "OST,PREDYEAR")]
		[TestCase("OST and OTKL", "OST,OTKL")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M12", "BYMONTH,FACT,ED,KOL,PRED,M12")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M12", "BYMONTH,FACT,ED,CENA,PRED,M12")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M12", "BYMONTH,FACT,ED,SUMMA,PRED,M12")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M12", "BYMONTH,FACT,VSEGO,KOL,PRED,M12")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M12", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M12")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M11", "BYMONTH,FACT,ED,KOL,PRED,M11")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M11", "BYMONTH,FACT,ED,CENA,PRED,M11")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M11", "BYMONTH,FACT,ED,SUMMA,PRED,M11")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M11", "BYMONTH,FACT,VSEGO,KOL,PRED,M11")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M11", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M11")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M10", "BYMONTH,FACT,ED,KOL,PRED,M10")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M10", "BYMONTH,FACT,ED,CENA,PRED,M10")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M10", "BYMONTH,FACT,ED,SUMMA,PRED,M10")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M10", "BYMONTH,FACT,VSEGO,KOL,PRED,M10")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M10", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M10")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M9", "BYMONTH,FACT,ED,KOL,PRED,M9")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M9", "BYMONTH,FACT,ED,CENA,PRED,M9")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M9", "BYMONTH,FACT,ED,SUMMA,PRED,M9")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M9", "BYMONTH,FACT,VSEGO,KOL,PRED,M9")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M9", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M9")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M8", "BYMONTH,FACT,ED,KOL,PRED,M8")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M8", "BYMONTH,FACT,ED,CENA,PRED,M8")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M8", "BYMONTH,FACT,ED,SUMMA,PRED,M8")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M8", "BYMONTH,FACT,VSEGO,KOL,PRED,M8")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M8", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M8")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M7", "BYMONTH,FACT,ED,KOL,PRED,M7")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M7", "BYMONTH,FACT,ED,CENA,PRED,M7")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M7", "BYMONTH,FACT,ED,SUMMA,PRED,M7")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M7", "BYMONTH,FACT,VSEGO,KOL,PRED,M7")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M7", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M7")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M6", "BYMONTH,FACT,ED,KOL,PRED,M6")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M6", "BYMONTH,FACT,ED,CENA,PRED,M6")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M6", "BYMONTH,FACT,ED,SUMMA,PRED,M6")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M6", "BYMONTH,FACT,VSEGO,KOL,PRED,M6")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M6", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M6")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M5", "BYMONTH,FACT,ED,KOL,PRED,M5")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M5", "BYMONTH,FACT,ED,CENA,PRED,M5")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M5", "BYMONTH,FACT,ED,SUMMA,PRED,M5")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M5", "BYMONTH,FACT,VSEGO,KOL,PRED,M5")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M5", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M5")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M4", "BYMONTH,FACT,ED,KOL,PRED,M4")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M4", "BYMONTH,FACT,ED,CENA,PRED,M4")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M4", "BYMONTH,FACT,ED,SUMMA,PRED,M4")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M4", "BYMONTH,FACT,VSEGO,KOL,PRED,M4")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M4", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M4")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M3", "BYMONTH,FACT,ED,KOL,PRED,M3")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M3", "BYMONTH,FACT,ED,CENA,PRED,M3")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M3", "BYMONTH,FACT,ED,SUMMA,PRED,M3")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M3", "BYMONTH,FACT,VSEGO,KOL,PRED,M3")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M3", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M3")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M2", "BYMONTH,FACT,ED,KOL,PRED,M2")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M2", "BYMONTH,FACT,ED,CENA,PRED,M2")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M2", "BYMONTH,FACT,ED,SUMMA,PRED,M2")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M2", "BYMONTH,FACT,VSEGO,KOL,PRED,M2")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M2", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M2")]
		[TestCase(" BYMONTH and PLAN and ED and KOL", "BYMONTH,PLAN,ED,KOL")]
		[TestCase(" BYMONTH and PLAN and ED and CENA", "BYMONTH,PLAN,ED,CENA")]
		[TestCase(" BYMONTH and PLAN and ED and SUMMA", "BYMONTH,PLAN,ED,SUMMA")]
		[TestCase(" BYMONTH and PLAN and VSEGO and KOL", "BYMONTH,PLAN,VSEGO,KOL")]
		[TestCase(" BYMONTH and PLAN and VSEGO and SUMMA", "BYMONTH,PLAN,VSEGO,SUMMA")]
		[TestCase("BYMONTH and FACT and ED and KOL and PRED and M1", "BYMONTH,FACT,ED,KOL,PRED,M1")]
		[TestCase("BYMONTH and FACT and ED and CENA and PRED and M1", "BYMONTH,FACT,ED,CENA,PRED,M1")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PRED and M1", "BYMONTH,FACT,ED,SUMMA,PRED,M1")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PRED and M1", "BYMONTH,FACT,VSEGO,KOL,PRED,M1")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PRED and M1", "BYMONTH,FACT,VSEGO,SUMMA,PRED,M1")]
		[TestCase("BYMONTH and FACT and ED and KOL", "BYMONTH,FACT,ED,KOL")]
		[TestCase("BYMONTH and FACT and ED and CENA", "BYMONTH,FACT,ED,CENA")]
		[TestCase("BYMONTH and FACT and ED and SUMMA", "BYMONTH,FACT,ED,SUMMA")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL", "BYMONTH,FACT,VSEGO,KOL")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA", "BYMONTH,FACT,VSEGO,SUMMA")]
		[TestCase("BYMONTH and FACT and ED and KOL and PLAN and OTKL", "BYMONTH,FACT,ED,KOL,PLAN,OTKL")]
		[TestCase("BYMONTH and FACT and ED and CENA and PLAN and OTKL", "BYMONTH,FACT,ED,CENA,PLAN,OTKL")]
		[TestCase("BYMONTH and FACT and ED and SUMMA and PLAN and OTKL", "BYMONTH,FACT,ED,SUMMA,PLAN,OTKL")]
		[TestCase("BYMONTH and FACT and VSEGO and KOL and PLAN and OTKL", "BYMONTH,FACT,VSEGO,KOL,PLAN,OTKL")]
		[TestCase("BYMONTH and FACT and VSEGO and SUMMA and PLAN and OTKL", "BYMONTH,FACT,VSEGO,SUMMA,PLAN,OTKL")]
		[TestCase("СНГ and FACT and ED and KOL and PREDYEAR", "СНГ,FACT,ED,KOL,PREDYEAR")]
		[TestCase("СНГ and FACT and ED and CENA and PREDYEAR", "СНГ,FACT,ED,CENA,PREDYEAR")]
		[TestCase("СНГ and FACT and ED and SUMMA and PREDYEAR", "СНГ,FACT,ED,SUMMA,PREDYEAR")]
		[TestCase("СНГ and FACT and VSEGO and KOL and PREDYEAR", "СНГ,FACT,VSEGO,KOL,PREDYEAR")]
		[TestCase("СНГ and FACT and VSEGO and SUMMA and PREDYEAR", "СНГ,FACT,VSEGO,SUMMA,PREDYEAR")]
		[TestCase(" СНГ and PLAN and ED and KOL", "СНГ,PLAN,ED,KOL")]
		[TestCase(" СНГ and PLAN and ED and CENA", "СНГ,PLAN,ED,CENA")]
		[TestCase(" СНГ and PLAN and ED and SUMMA", "СНГ,PLAN,ED,SUMMA")]
		[TestCase(" СНГ and PLAN and VSEGO and KOL", "СНГ,PLAN,VSEGO,KOL")]
		[TestCase(" СНГ and PLAN and VSEGO and SUMMA", "СНГ,PLAN,VSEGO,SUMMA")]
		[TestCase("СНГ and FACT and ED and KOL", "СНГ,FACT,ED,KOL")]
		[TestCase("СНГ and FACT and ED and CENA", "СНГ,FACT,ED,CENA")]
		[TestCase("СНГ and FACT and ED and SUMMA", "СНГ,FACT,ED,SUMMA")]
		[TestCase("СНГ and FACT and VSEGO and KOL", "СНГ,FACT,VSEGO,KOL")]
		[TestCase("СНГ and FACT and VSEGO and SUMMA", "СНГ,FACT,VSEGO,SUMMA")]
		[TestCase("СНГ and FACT and ED and KOL and PLAN and OTKL", "СНГ,FACT,ED,KOL,PLAN,OTKL")]
		[TestCase("СНГ and FACT and ED and CENA and PLAN and OTKL", "СНГ,FACT,ED,CENA,PLAN,OTKL")]
		[TestCase("СНГ and FACT and ED and SUMMA and PLAN and OTKL", "СНГ,FACT,ED,SUMMA,PLAN,OTKL")]
		[TestCase("СНГ and FACT and VSEGO and KOL and PLAN and OTKL", "СНГ,FACT,VSEGO,KOL,PLAN,OTKL")]
		[TestCase("СНГ and FACT and VSEGO and SUMMA and PLAN and OTKL", "СНГ,FACT,VSEGO,SUMMA,PLAN,OTKL")]
		[TestCase("PLAN and SUMMAEDD and USETPFP", "PLAN,SUMMAEDD,USETPFP")]
		[TestCase("PLAN and SUMMAEDR and USETPFP", "PLAN,SUMMAEDR,USETPFP")]
		[TestCase("PLAN and SUMMAR and USETPFP", "PLAN,SUMMAR,USETPFP")]
		[TestCase("FACT and SUMMAEDD and M6", "FACT,SUMMAEDD,M6")]
		[TestCase("FACT and SUMMAEDR and M6", "FACT,SUMMAEDR,M6")]
		[TestCase("FACT and SUMMAR and M6", "FACT,SUMMAR,M6")]
		[TestCase("FACT and SUMMAEDD and M5", "FACT,SUMMAEDD,M5")]
		[TestCase("FACT and SUMMAEDR and M5", "FACT,SUMMAEDR,M5")]
		[TestCase("FACT and SUMMAR and M5", "FACT,SUMMAR,M5")]
		[TestCase("FACT and SUMMAEDD and M4", "FACT,SUMMAEDD,M4")]
		[TestCase("FACT and SUMMAEDR and M4", "FACT,SUMMAEDR,M4")]
		[TestCase("FACT and SUMMAR and M4", "FACT,SUMMAR,M4")]
		[TestCase("FACT and SUMMAEDD and M3", "FACT,SUMMAEDD,M3")]
		[TestCase("FACT and SUMMAEDR and M3", "FACT,SUMMAEDR,M3")]
		[TestCase("FACT and SUMMAR and M3", "FACT,SUMMAR,M3")]
		[TestCase("FACT and SUMMAEDD and M2", "FACT,SUMMAEDD,M2")]
		[TestCase("FACT and SUMMAEDR and M2", "FACT,SUMMAEDR,M2")]
		[TestCase("FACT and SUMMAR and M2", "FACT,SUMMAR,M2")]
		[TestCase("FACT and SUMMAEDD and M1", "FACT,SUMMAEDD,M1")]
		[TestCase("FACT and SUMMAEDR and M1", "FACT,SUMMAEDR,M1")]
		[TestCase("FACT and SUMMAR and M1", "FACT,SUMMAR,M1")]
		[TestCase("FACT and SUMMAEDD and BYMONTH", "FACT,SUMMAEDD,BYMONTH")]
		[TestCase("FACT and SUMMAEDR and BYMONTH", "FACT,SUMMAEDR,BYMONTH")]
		[TestCase("FACT and SUMMAR and BYMONTH", "FACT,SUMMAR,BYMONTH")]
		[TestCase("PLAN and SUMMAEDD and СНГ", "PLAN,SUMMAEDD,СНГ")]
		[TestCase("PLAN and SUMMAEDR and СНГ", "PLAN,SUMMAEDR,СНГ")]
		[TestCase("PLAN and SUMMAR and СНГ", "PLAN,SUMMAR,СНГ")]
		[TestCase("FACT and SUMMAEDD and СНГ", "FACT,SUMMAEDD,СНГ")]
		[TestCase("FACT and SUMMAEDR and СНГ", "FACT,SUMMAEDR,СНГ")]
		[TestCase("FACT and SUMMAR and СНГ", "FACT,SUMMAR,СНГ")]
		[TestCase("FACT and ED and KOL", "FACT,ED,KOL")]
		[TestCase("FACT and ED and CENA", "FACT,ED,CENA")]
		[TestCase("FACT and ED and SUMMA", "FACT,ED,SUMMA")]
		[TestCase("FACT and VSEGO and KOL", "FACT,VSEGO,KOL")]
		[TestCase("FACT and VSEGO and SUMMA", "FACT,VSEGO,SUMMA")]
		[TestCase(" PLAN and ED and KOL", "PLAN,ED,KOL")]
		[TestCase(" PLAN and ED and CENA", "PLAN,ED,CENA")]
		[TestCase(" PLAN and ED and SUMMA", "PLAN,ED,SUMMA")]
		[TestCase(" PLAN and VSEGO and KOL", "PLAN,VSEGO,KOL")]
		[TestCase(" PLAN and VSEGO and SUMMA", "PLAN,VSEGO,SUMMA")]
		[TestCase("Y2 and FACT and SUMMAEDD", "Y2,FACT,SUMMAEDD")]
		[TestCase("Y2 and FACT and SUMMAEDR", "Y2,FACT,SUMMAEDR")]
		[TestCase("Y2 and FACT and SUMMAR", "Y2,FACT,SUMMAR")]
		[TestCase("Y1 and PLAN and SUMMAEDD", "Y1,PLAN,SUMMAEDD")]
		[TestCase("Y1 and PLAN and SUMMAEDR", "Y1,PLAN,SUMMAEDR")]
		[TestCase("Y1 and PLAN and SUMMAR", "Y1,PLAN,SUMMAR")]
		[TestCase("Y1 and FACT and SUMMAEDD", "Y1,FACT,SUMMAEDD")]
		[TestCase("Y1 and FACT and SUMMAEDR", "Y1,FACT,SUMMAEDR")]
		[TestCase("Y1 and FACT and SUMMAR", "Y1,FACT,SUMMAR")]
		[TestCase("PLAN and SUMMAEDD", "PLAN,SUMMAEDD")]
		[TestCase("PLAN and SUMMAEDR", "PLAN,SUMMAEDR")]
		[TestCase("PLAN and SUMMAR", "PLAN,SUMMAR")]
		[TestCase("SUMMAEDD and Y3", "SUMMAEDD,Y3")]
		[TestCase("SUMMAEDR and Y3", "SUMMAEDR,Y3")]
		[TestCase("SUMMAR and Y3", "SUMMAR,Y3")]
		[TestCase("SUMMAEDD and Y2", "SUMMAEDD,Y2")]
		[TestCase("SUMMAEDR and Y2", "SUMMAEDR,Y2")]
		[TestCase("SUMMAR and Y2", "SUMMAR,Y2")]
		[TestCase("SUMMAEDD and Y1", "SUMMAEDD,Y1")]
		[TestCase("SUMMAEDR and Y1", "SUMMAEDR,Y1")]
		[TestCase("SUMMAR and Y1", "SUMMAR,Y1")]
		[TestCase("SUMMAEDD and PRED  and M6", "SUMMAEDD,PRED,M6")]
		[TestCase("SUMMAEDR and PRED  and M6", "SUMMAEDR,PRED,M6")]
		[TestCase("SUMMAR and PRED  and M6", "SUMMAR,PRED,M6")]
		[TestCase("SUMMAEDD and PRED and M5", "SUMMAEDD,PRED,M5")]
		[TestCase("SUMMAEDR and PRED and M5", "SUMMAEDR,PRED,M5")]
		[TestCase("SUMMAR and PRED and M5", "SUMMAR,PRED,M5")]
		[TestCase("SUMMAEDD and PRED and M4", "SUMMAEDD,PRED,M4")]
		[TestCase("SUMMAEDR and PRED and M4", "SUMMAEDR,PRED,M4")]
		[TestCase("SUMMAR and PRED and M4", "SUMMAR,PRED,M4")]
		[TestCase("SUMMAEDD and M3", "SUMMAEDD,M3")]
		[TestCase("SUMMAEDR and M3", "SUMMAEDR,M3")]
		[TestCase("SUMMAR and M3", "SUMMAR,M3")]
		[TestCase("SUMMAEDD and PRED and M2", "SUMMAEDD,PRED,M2")]
		[TestCase("SUMMAEDR and PRED and M2", "SUMMAEDR,PRED,M2")]
		[TestCase("SUMMAR and PRED and M2", "SUMMAR,PRED,M2")]
		[TestCase("SUMMAEDD and PRED and M1 ", "SUMMAEDD,PRED,M1")]
		[TestCase("SUMMAEDR and PRED and M1 ", "SUMMAEDR,PRED,M1")]
		[TestCase("SUMMAR and PRED and M1 ", "SUMMAR,PRED,M1")]
		[TestCase("SUMMAEDD and СНГ and FACT", "SUMMAEDD,СНГ,FACT")]
		[TestCase("SUMMAEDR and СНГ and FACT", "SUMMAEDR,СНГ,FACT")]
		[TestCase("SUMMAR and СНГ and FACT", "SUMMAR,СНГ,FACT")]
		[TestCase("SUMMAEDD and СНГ and OZHID", "SUMMAEDD,СНГ,OZHID")]
		[TestCase("SUMMAEDR and СНГ and OZHID", "SUMMAEDR,СНГ,OZHID")]
		[TestCase("SUMMAR and СНГ and OZHID", "SUMMAR,СНГ,OZHID")]
		[TestCase("DZ and СНГ and PREDYEAR", "DZ,СНГ,PREDYEAR")]
		[TestCase("DZ and RESERV and СНГ and PREDYEAR", "DZ,RESERV,СНГ,PREDYEAR")]
		[TestCase("KZ and СНГ and PREDYEAR", "KZ,СНГ,PREDYEAR")]
		[TestCase("DZ and BYMONTH", "DZ,BYMONTH")]
		[TestCase("DZ and RESERV and BYMONTH", "DZ,RESERV,BYMONTH")]
		[TestCase("KZ and BYMONTH", "KZ,BYMONTH")]
		[TestCase("DZ and СНГ", "DZ,СНГ")]
		[TestCase("DZ and RESERV and СНГ", "DZ,RESERV,СНГ")]
		[TestCase("KZ and СНГ", "KZ,СНГ")]
		[TestCase("DZ and ( BYMONTH or СНГ )", "DZ,BYMONTH,СНГ")]
		[TestCase("DZ and RESERV and ( BYMONTH or СНГ )", "DZ,RESERV,BYMONTH,СНГ")]
		[TestCase("KZ and ( BYMONTH or СНГ )", "KZ,BYMONTH,СНГ")]
		[TestCase("DZ and OTKL and BYMONTH", "DZ,OTKL,BYMONTH")]
		[TestCase("DZ and RESERV and OTKL and BYMONTH", "DZ,RESERV,OTKL,BYMONTH")]
		[TestCase("KZ and OTKL and BYMONTH", "KZ,OTKL,BYMONTH")]
		[TestCase("DZ and OTKL and СНГ", "DZ,OTKL,СНГ")]
		[TestCase("DZ and RESERV and OTKL and СНГ ", "DZ,RESERV,OTKL,СНГ")]
		[TestCase("KZ and OTKL and СНГ ", "KZ,OTKL,СНГ")]
		[TestCase("DZ and OTKL", "DZ,OTKL")]
		[TestCase("KZ and OTKL", "KZ,OTKL")]
		[TestCase("Y12 and KOL", "Y12,KOL")]
		[TestCase("Y12 and CENA", "Y12,CENA")]
		[TestCase("Y12 and SUMMA", "Y12,SUMMA")]
		[TestCase("Y11 and KOL", "Y11,KOL")]
		[TestCase("Y11 and CENA", "Y11,CENA")]
		[TestCase("Y11 and SUMMA", "Y11,SUMMA")]
		[TestCase("Y10 and KOL", "Y10,KOL")]
		[TestCase("Y10 and CENA", "Y10,CENA")]
		[TestCase("Y10 and SUMMA", "Y10,SUMMA")]
		[TestCase("Y9 and KOL", "Y9,KOL")]
		[TestCase("Y9 and CENA", "Y9,CENA")]
		[TestCase("Y9 and SUMMA", "Y9,SUMMA")]
		[TestCase("Y8 and KOL", "Y8,KOL")]
		[TestCase("Y8 and CENA", "Y8,CENA")]
		[TestCase("Y8 and SUMMA", "Y8,SUMMA")]
		[TestCase("Y7 and KOL", "Y7,KOL")]
		[TestCase("Y7 and CENA", "Y7,CENA")]
		[TestCase("Y7 and SUMMA", "Y7,SUMMA")]
		[TestCase("Y6 and KOL", "Y6,KOL")]
		[TestCase("Y6 and CENA", "Y6,CENA")]
		[TestCase("Y6 and SUMMA", "Y6,SUMMA")]
		[TestCase("Y5 and KOL", "Y5,KOL")]
		[TestCase("Y5 and CENA", "Y5,CENA")]
		[TestCase("Y5 and SUMMA", "Y5,SUMMA")]
		[TestCase("Y4 and KOL", "Y4,KOL")]
		[TestCase("Y4 and CENA", "Y4,CENA")]
		[TestCase("Y4 and SUMMA", "Y4,SUMMA")]
		[TestCase("Y3 and KOL", "Y3,KOL")]
		[TestCase("Y3 and CENA", "Y3,CENA")]
		[TestCase("Y3 and SUMMA", "Y3,SUMMA")]
		[TestCase("Y2 and KOL", "Y2,KOL")]
		[TestCase("Y2 and CENA", "Y2,CENA")]
		[TestCase("Y2 and SUMMA", "Y2,SUMMA")]
		[TestCase("Y2 and UDVESZATR and SUMMA", "Y2,UDVESZATR,SUMMA")]
		[TestCase("Y2 and UDVESPERED and SUMMA", "Y2,UDVESPERED,SUMMA")]
		[TestCase("Y1 and KOL", "Y1,KOL")]
		[TestCase("Y1 and CENA", "Y1,CENA")]
		[TestCase("Y1 and SUMMA", "Y1,SUMMA")]
		[TestCase("PREDYEAR and KOL", "PREDYEAR,KOL")]
		[TestCase("PREDYEAR and CENA", "PREDYEAR,CENA")]
		[TestCase("PREDYEAR and SUMMA", "PREDYEAR,SUMMA")]
		[TestCase("PREDYEAR and UDVESZATR and SUMMA", "PREDYEAR,UDVESZATR,SUMMA")]
		[TestCase("PREDYEAR and UDVESPERED and SUMMA", "PREDYEAR,UDVESPERED,SUMMA")]
		[TestCase("USETPFP and KOL", "USETPFP,KOL")]
		[TestCase("USETPFP and CENA", "USETPFP,CENA")]
		[TestCase("USETPFP and SUMMA", "USETPFP,SUMMA")]
		[TestCase("PLAN and KOL", "PLAN,KOL")]
		[TestCase("PLAN and CENA", "PLAN,CENA")]
		[TestCase("PLAN and SUMMA", "PLAN,SUMMA")]
		[TestCase("FACT and KOL", "FACT,KOL")]
		[TestCase("FACT and CENA", "FACT,CENA")]
		[TestCase("FACT and SUMMA", "FACT,SUMMA")]
		[TestCase("FACT and UDVESZATR and SUMMA", "FACT,UDVESZATR,SUMMA")]
		[TestCase("FACT and UDVESPERED and SUMMA", "FACT,UDVESPERED,SUMMA")]
		[TestCase("PLAN and UDVESZATR and SUMMA", "PLAN,UDVESZATR,SUMMA")]
		[TestCase("PLAN and UDVESPERED and SUMMA", "PLAN,UDVESPERED,SUMMA")]
		[TestCase("( OZHID or PLAN ) and KOL", "OZHID,PLAN,KOL")]
		[TestCase("( OZHID or PLAN )  and CENA", "OZHID,PLAN,CENA")]
		[TestCase("( OZHID or PLAN ) and SUMMA", "OZHID,PLAN,SUMMA")]
		[TestCase("FACT and OTKL and PREDYEAR and OTKLABS ", "FACT,OTKL,PREDYEAR,OTKLABS")]
		[TestCase("FACT and OTKL and PLAN and OTKLABS ", "FACT,OTKL,PLAN,OTKLABS")]
		[TestCase(" PLAN and OTKL and OTKLFA and Y1 and OTKLABS ", "PLAN,OTKL,OTKLFA,Y1,OTKLABS")]
		[TestCase("FACT and PLAN and OTKL and Y1 and OTKLABS ", "FACT,PLAN,OTKL,Y1,OTKLABS")]
		[TestCase(" FACT and PLAN and OTKL and OTKLFA and Y1 and OTKLABS ", "FACT,PLAN,OTKL,OTKLFA,Y1,OTKLABS")]
		[TestCase("OTKL and FACT and Y1 and PLAN and PRIROST", "OTKL,FACT,Y1,PLAN,PRIROST")]
		[TestCase("OTKL and Y1 and PLAN and PRIROST", "OTKL,Y1,PLAN,PRIROST")]
		[TestCase("FACT and OTKL and PREDYEAR and OTKLOTN ", "FACT,OTKL,PREDYEAR,OTKLOTN")]
		[TestCase("FACT and OTKL and PLAN and OTKLOTN ", "FACT,OTKL,PLAN,OTKLOTN")]
		[TestCase("Y2 and KOL and PRIHOD", "Y2,KOL,PRIHOD")]
		[TestCase("Y2 and CENA and PRIHOD", "Y2,CENA,PRIHOD")]
		[TestCase("Y2 and SUMMA and PRIHOD", "Y2,SUMMA,PRIHOD")]
		[TestCase("Y1 and PLAN and KOL and PRIHOD", "Y1,PLAN,KOL,PRIHOD")]
		[TestCase("Y1 and PLAN and CENA and PRIHOD", "Y1,PLAN,CENA,PRIHOD")]
		[TestCase("Y1 and PLAN and SUMMA and PRIHOD", "Y1,PLAN,SUMMA,PRIHOD")]
		[TestCase("Y1 and FACT and KOL and PRIHOD", "Y1,FACT,KOL,PRIHOD")]
		[TestCase("Y1 and FACT  and CENA and PRIHOD", "Y1,FACT,CENA,PRIHOD")]
		[TestCase("Y1 and FACT and SUMMA and PRIHOD", "Y1,FACT,SUMMA,PRIHOD")]
		[TestCase("PLAN and KOL and PRIHOD", "PLAN,KOL,PRIHOD")]
		[TestCase("PLAN and CENA and PRIHOD", "PLAN,CENA,PRIHOD")]
		[TestCase("Y2 and KOL and RASHOD", "Y2,KOL,RASHOD")]
		[TestCase("Y2 and CENA and RASHOD", "Y2,CENA,RASHOD")]
		[TestCase("Y2 and SUMMA and RASHOD", "Y2,SUMMA,RASHOD")]
		[TestCase("Y1 and PLAN and KOL and RASHOD", "Y1,PLAN,KOL,RASHOD")]
		[TestCase("Y1 and PLAN and CENA and RASHOD", "Y1,PLAN,CENA,RASHOD")]
		[TestCase("Y1 and PLAN and SUMMA and RASHOD", "Y1,PLAN,SUMMA,RASHOD")]
		[TestCase("Y1 and FACT and KOL and RASHOD", "Y1,FACT,KOL,RASHOD")]
		[TestCase("Y1 and FACT  and CENA and RASHOD", "Y1,FACT,CENA,RASHOD")]
		[TestCase("Y1 and FACT and SUMMA and RASHOD", "Y1,FACT,SUMMA,RASHOD")]
		[TestCase("PLAN and KOL and RASHOD", "PLAN,KOL,RASHOD")]
		[TestCase("PLAN and CENA and RASHOD", "PLAN,CENA,RASHOD")]
		[TestCase("PLAN and SUMMA and RASHOD", "PLAN,SUMMA,RASHOD")]
		[TestCase("OST and Y8", "OST,Y8")]
		[TestCase("NACH and Y8", "NACH,Y8")]
		[TestCase("NACH and USEKORR and Y8", "NACH,USEKORR,Y8")]
		[TestCase("OPL and Y8", "OPL,Y8")]
		[TestCase("OST and Y7", "OST,Y7")]
		[TestCase("NACH and Y7", "NACH,Y7")]
		[TestCase("NACH and USEKORR and Y7", "NACH,USEKORR,Y7")]
		[TestCase("OPL and Y7", "OPL,Y7")]
		[TestCase("OST and Y6", "OST,Y6")]
		[TestCase("NACH and Y6", "NACH,Y6")]
		[TestCase("NACH and USEKORR and Y6", "NACH,USEKORR,Y6")]
		[TestCase("OPL and Y6", "OPL,Y6")]
		[TestCase("OST and Y5", "OST,Y5")]
		[TestCase("NACH and Y5", "NACH,Y5")]
		[TestCase("NACH and USEKORR and Y5", "NACH,USEKORR,Y5")]
		[TestCase("OPL and Y5", "OPL,Y5")]
		[TestCase("OST and Y4", "OST,Y4")]
		[TestCase("NACH and Y4", "NACH,Y4")]
		[TestCase("NACH and USEKORR and Y4", "NACH,USEKORR,Y4")]
		[TestCase("OPL and Y4", "OPL,Y4")]
		[TestCase("OST and Y3", "OST,Y3")]
		[TestCase("NACH and Y3", "NACH,Y3")]
		[TestCase("NACH and USEKORR and Y3", "NACH,USEKORR,Y3")]
		[TestCase("OPL and Y3", "OPL,Y3")]
		[TestCase("OST and Y2", "OST,Y2")]
		[TestCase("NACH and Y2", "NACH,Y2")]
		[TestCase("NACH and USEKORR and Y2", "NACH,USEKORR,Y2")]
		[TestCase("OPL and Y2", "OPL,Y2")]
		[TestCase("OST and Y1", "OST,Y1")]
		[TestCase("NACH and Y1", "NACH,Y1")]
		[TestCase("NACH and USEKORR and Y1", "NACH,USEKORR,Y1")]
		[TestCase("OPL and Y1", "OPL,Y1")]
		[TestCase("OST and Y2 and OTKL", "OST,Y2,OTKL")]
		[TestCase("NACH and Y2 and OTKL", "NACH,Y2,OTKL")]
		[TestCase("NACH and USEKORR and Y2 and OTKL", "NACH,USEKORR,Y2,OTKL")]
		[TestCase("OPL and Y2 and OTKL", "OPL,Y2,OTKL")]
		[TestCase("NACH or OPL", "NACH,OPL")]
		[TestCase("OST and BYMONTH and PRED and M12", "OST,BYMONTH,PRED,M12")]
		[TestCase("NACH and BYMONTH and PRED and M12", "NACH,BYMONTH,PRED,M12")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M12", "NACH,BYMONTH,USEKORR,PRED,M12")]
		[TestCase("OPL and BYMONTH and PRED and M12", "OPL,BYMONTH,PRED,M12")]
		[TestCase("OST and BYMONTH and PRED and M11", "OST,BYMONTH,PRED,M11")]
		[TestCase("NACH and BYMONTH and PRED and M11", "NACH,BYMONTH,PRED,M11")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M11", "NACH,BYMONTH,USEKORR,PRED,M11")]
		[TestCase("OPL and BYMONTH and PRED and M11", "OPL,BYMONTH,PRED,M11")]
		[TestCase("OST and BYMONTH and PRED and M10", "OST,BYMONTH,PRED,M10")]
		[TestCase("NACH and BYMONTH and PRED and M10", "NACH,BYMONTH,PRED,M10")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M10", "NACH,BYMONTH,USEKORR,PRED,M10")]
		[TestCase("OPL and BYMONTH and PRED and M10", "OPL,BYMONTH,PRED,M10")]
		[TestCase("OST and BYMONTH and PRED and M9", "OST,BYMONTH,PRED,M9")]
		[TestCase("NACH and BYMONTH and PRED and M9", "NACH,BYMONTH,PRED,M9")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M9", "NACH,BYMONTH,USEKORR,PRED,M9")]
		[TestCase("OPL and BYMONTH and PRED and M9", "OPL,BYMONTH,PRED,M9")]
		[TestCase("OST and BYMONTH and PRED and M8", "OST,BYMONTH,PRED,M8")]
		[TestCase("NACH and BYMONTH and PRED and M8", "NACH,BYMONTH,PRED,M8")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M8", "NACH,BYMONTH,USEKORR,PRED,M8")]
		[TestCase("OPL and BYMONTH and PRED and M8", "OPL,BYMONTH,PRED,M8")]
		[TestCase("OST and BYMONTH and PRED and M7", "OST,BYMONTH,PRED,M7")]
		[TestCase("NACH and BYMONTH and PRED and M7", "NACH,BYMONTH,PRED,M7")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M7", "NACH,BYMONTH,USEKORR,PRED,M7")]
		[TestCase("OPL and BYMONTH and PRED and M7", "OPL,BYMONTH,PRED,M7")]
		[TestCase("OST and BYMONTH and PRED and M6", "OST,BYMONTH,PRED,M6")]
		[TestCase("NACH and BYMONTH and PRED and M6", "NACH,BYMONTH,PRED,M6")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M6", "NACH,BYMONTH,USEKORR,PRED,M6")]
		[TestCase("OPL and BYMONTH and PRED and M6", "OPL,BYMONTH,PRED,M6")]
		[TestCase("OST and BYMONTH and PRED and M5", "OST,BYMONTH,PRED,M5")]
		[TestCase("NACH and BYMONTH and PRED and M5", "NACH,BYMONTH,PRED,M5")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M5", "NACH,BYMONTH,USEKORR,PRED,M5")]
		[TestCase("OPL and BYMONTH and PRED and M5", "OPL,BYMONTH,PRED,M5")]
		[TestCase("OST and BYMONTH and PRED and M4", "OST,BYMONTH,PRED,M4")]
		[TestCase("NACH and BYMONTH and PRED and M4", "NACH,BYMONTH,PRED,M4")]
		[TestCase("NACH and BYMONTH and USEKORR and PRED and M4", "NACH,BYMONTH,USEKORR,PRED,M4")]
		[TestCase("OPL and BYMONTH and PRED and M4", "OPL,BYMONTH,PRED,M4")]
		[TestCase("OST and BYMONTH and PRED and M3", "OST,BYMONTH,PRED,M3")]
		[TestCase("NACH and BYMONTH and PRED and M3", "NACH,BYMONTH,PRED,M3")]
		[TestCase("NACH and BYMONTH and PRED and USEKORR and M3", "NACH,BYMONTH,PRED,USEKORR,M3")]
		[TestCase("OPL and BYMONTH and PRED and M3", "OPL,BYMONTH,PRED,M3")]
		[TestCase("OST and BYMONTH and PRED and M2", "OST,BYMONTH,PRED,M2")]
		[TestCase("NACH and BYMONTH and PRED and M2", "NACH,BYMONTH,PRED,M2")]
		[TestCase("NACH and BYMONTH and PRED and USEKORR and M2", "NACH,BYMONTH,PRED,USEKORR,M2")]
		[TestCase("OPL and BYMONTH and PRED and M2", "OPL,BYMONTH,PRED,M2")]
		[TestCase("OST and BYMONTH and PREDYEAR", "OST,BYMONTH,PREDYEAR")]
		[TestCase("NACH and BYMONTH and PREDYEAR", "NACH,BYMONTH,PREDYEAR")]
		[TestCase("NACH and BYMONTH and USEKORR and PREDYEAR", "NACH,BYMONTH,USEKORR,PREDYEAR")]
		[TestCase("OPL and BYMONTH and PREDYEAR", "OPL,BYMONTH,PREDYEAR")]
		[TestCase("OST and СНГ and PREDYEAR", "OST,СНГ,PREDYEAR")]
		[TestCase("NACH and СНГ and PREDYEAR", "NACH,СНГ,PREDYEAR")]
		[TestCase("NACH and СНГ and USEKORR and PREDYEAR", "NACH,СНГ,USEKORR,PREDYEAR")]
		[TestCase("OPL and СНГ and PREDYEAR", "OPL,СНГ,PREDYEAR")]
		[TestCase("NACH and Y2 and USEKORR", "NACH,Y2,USEKORR")]
		[TestCase("NACH and Y1 and USEKORR", "NACH,Y1,USEKORR")]
		[TestCase("OST and СНГ and PREDYEAR and OTKL", "OST,СНГ,PREDYEAR,OTKL")]
		[TestCase("NACH and СНГ and PREDYEAR and OTKL", "NACH,СНГ,PREDYEAR,OTKL")]
		[TestCase("NACH and СНГ and USEKORR and PREDYEAR and OTKL", "NACH,СНГ,USEKORR,PREDYEAR,OTKL")]
		[TestCase("OPL and СНГ and PREDYEAR and OTKL", "OPL,СНГ,PREDYEAR,OTKL")]
		[TestCase("OST and M12", "OST,M12")]
		[TestCase("NACH and M12", "NACH,M12")]
		[TestCase("OPL and M12", "OPL,M12")]
		[TestCase("NACH and M6", "NACH,M6")]
		[TestCase("OPL and M6", "OPL,M6")]
		[TestCase("OST and not M12", "OST,M12")]
		[TestCase("OST and KVARTRAS and M2", "OST,KVARTRAS,M2")]
		[TestCase("NACH and KVARTRAS", "NACH,KVARTRAS")]
		[TestCase("NACH and USEKORR and KVARTRAS and M2 and M2", "NACH,USEKORR,KVARTRAS,M2")]
		[TestCase("OPL and KVARTRAS and M2", "OPL,KVARTRAS,M2")]
		[TestCase("OST and KVARTRAS and M5", "OST,KVARTRAS,M5")]
		[TestCase("NACH and KVARTRAS and M5", "NACH,KVARTRAS,M5")]
		[TestCase("NACH and USEKORR and KVARTRAS and M5", "NACH,USEKORR,KVARTRAS,M5")]
		[TestCase("OPL and KVARTRAS and M5", "OPL,KVARTRAS,M5")]
		[TestCase("NACH and KVARTRAS and M2", "NACH,KVARTRAS,M2")]
		[TestCase("NACH and USEKORR and KVARTRAS and M2", "NACH,USEKORR,KVARTRAS,M2")]
		[TestCase("OST and KVARTRAS and M8", "OST,KVARTRAS,M8")]
		[TestCase("NACH and KVARTRAS and M8", "NACH,KVARTRAS,M8")]
		[TestCase("NACH and USEKORR and KVARTRAS and M8", "NACH,USEKORR,KVARTRAS,M8")]
		[TestCase("OPL and KVARTRAS and M8", "OPL,KVARTRAS,M8")]
		[TestCase("OST and KVARTRAS and M11", "OST,KVARTRAS,M11")]
		[TestCase("NACH and KVARTRAS and M11", "NACH,KVARTRAS,M11")]
		[TestCase("NACH and USEKORR and KVARTRAS and M11", "NACH,USEKORR,KVARTRAS,M11")]
		[TestCase("OPL and KVARTRAS and M11", "OPL,KVARTRAS,M11")]
		[TestCase("OST and yc10", "OST,yc10")]
		[TestCase("NACH and yc10", "NACH,yc10")]
		[TestCase("NACH and USEKORR and yc10", "NACH,USEKORR,yc10")]
		[TestCase("OPL and yc10", "OPL,yc10")]
		[TestCase("OST and yc9", "OST,yc9")]
		[TestCase("NACH and yc9", "NACH,yc9")]
		[TestCase("NACH and USEKORR and yc9", "NACH,USEKORR,yc9")]
		[TestCase("OPL and yc9", "OPL,yc9")]
		[TestCase("OST and yc8", "OST,yc8")]
		[TestCase("NACH and yc8", "NACH,yc8")]
		[TestCase("NACH and USEKORR and yc8", "NACH,USEKORR,yc8")]
		[TestCase("OPL and yc8", "OPL,yc8")]
		[TestCase("OST and yc7", "OST,yc7")]
		[TestCase("NACH and yc7", "NACH,yc7")]
		[TestCase("NACH and USEKORR and yc7", "NACH,USEKORR,yc7")]
		[TestCase("OPL and yc7", "OPL,yc7")]
		[TestCase("OST and yc6", "OST,yc6")]
		[TestCase("NACH and yc6", "NACH,yc6")]
		[TestCase("NACH and USEKORR and yc6", "NACH,USEKORR,yc6")]
		[TestCase("OPL and yc6", "OPL,yc6")]
		[TestCase("OST and yc5", "OST,yc5")]
		[TestCase("NACH and yc5", "NACH,yc5")]
		[TestCase("NACH and USEKORR and yc5", "NACH,USEKORR,yc5")]
		[TestCase("OPL and yc5", "OPL,yc5")]
		[TestCase("OST and yc4", "OST,yc4")]
		[TestCase("NACH and yc4", "NACH,yc4")]
		[TestCase("NACH and USEKORR and yc4", "NACH,USEKORR,yc4")]
		[TestCase("OPL and yc4", "OPL,yc4")]
		[TestCase("OST and yc3", "OST,yc3")]
		[TestCase("NACH and yc3", "NACH,yc3")]
		[TestCase("NACH and USEKORR and yc3", "NACH,USEKORR,yc3")]
		[TestCase("OPL and yc3", "OPL,yc3")]
		[TestCase("OST and yc2", "OST,yc2")]
		[TestCase("NACH and yc2", "NACH,yc2")]
		[TestCase("NACH and USEKORR,yc2", "NACH,USEKORR,yc2")]
		[TestCase("OPL and yc2", "OPL,yc2")]
		[TestCase("NACH and yc1", "NACH,yc1")]
		[TestCase("PRED and FACT and OTKL", "PRED,FACT,OTKL")]
		[TestCase("PLAN and FACT and BYMONTH and OTKL ", "PLAN,FACT,BYMONTH,OTKL")]
		[TestCase("FACT and СНГ and OTKL ", "FACT,СНГ,OTKL")]
		[TestCase("PLAN and FACT and СНГ and OTKL", "PLAN,FACT,СНГ,OTKL")]
		[TestCase("not KVKURS and PLANPRED and PLAN and not USEKORRTPFP", "KVKURS,PLANPRED,PLAN,USEKORRTPFP")]
		[TestCase("not KVKURS and PLANPRED and PLAN and USEKORRTPFP ", "KVKURS,PLANPRED,PLAN,USEKORRTPFP")]
		[TestCase("KVKURS and PLANPRED and PLAN", "KVKURS,PLANPRED,PLAN")]
		[TestCase("PLANPRED and PLAN and USEKORRTPFP and SHOWKORRTPFP", "PLANPRED,PLAN,USEKORRTPFP,SHOWKORRTPFP")]
		[TestCase("PLANPRED and PLAN and not USEKORRTPFP and SHOWKORRTPFP", "PLANPRED,PLAN,USEKORRTPFP,SHOWKORRTPFP")]
		[TestCase("PREDYEAR and ( OZHID or FACT )", "PREDYEAR,OZHID,FACT")]
		[TestCase("P1 and PLAN", "P1,PLAN")]
		[TestCase("P2 and PLAN", "P2,PLAN")]
		[TestCase("P3 and PLAN", "P3,PLAN")]
		[TestCase("not KVKURS and PLANPRED and OTKL and PLAN and USEKORRTPFP", "KVKURS,PLANPRED,OTKL,PLAN,USEKORRTPFP")]
		[TestCase("not KVKURS and PLANPRED and OTKL and PLAN and not USEKORRTPFP", "KVKURS,PLANPRED,OTKL,PLAN,USEKORRTPFP")]
		[TestCase("KVKURS and PLANPRED and OTKL and PLAN", "KVKURS,PLANPRED,OTKL,PLAN")]
		[TestCase("OTKL and PREDYEAR and PLAN and ( OZHID or FACT ) ", "OTKL,PREDYEAR,PLAN,OZHID,FACT")]
		[TestCase("FACT ", "FACT")]
		[TestCase("СНГ and Y12", "СНГ,Y12")]
		[TestCase("СНГ and Y11", "СНГ,Y11")]
		[TestCase("СНГ and Y10", "СНГ,Y10")]
		[TestCase("СНГ and Y9", "СНГ,Y9")]
		[TestCase("СНГ and Y8", "СНГ,Y8")]
		[TestCase("СНГ and Y7", "СНГ,Y7")]
		[TestCase("СНГ and Y6", "СНГ,Y6")]
		[TestCase("СНГ and Y5", "СНГ,Y5")]
		[TestCase("СНГ and Y4", "СНГ,Y4")]
		[TestCase("СНГ and Y3", "СНГ,Y3")]
		[TestCase("СНГ and Y2", "СНГ,Y2")]
		[TestCase("СНГ and Y1 and FACT", "СНГ,Y1,FACT")]
		[TestCase("FACT and PREDYEAR and СНГ", "FACT,PREDYEAR,СНГ")]
		[TestCase("OZHID and СНГ", "OZHID,СНГ")]
		[TestCase("FACT and BYMONTH and M12", "FACT,BYMONTH,M12")]
		[TestCase("FACT and BYMONTH and M11", "FACT,BYMONTH,M11")]
		[TestCase("FACT and BYMONTH and M10", "FACT,BYMONTH,M10")]
		[TestCase("FACT and BYMONTH and M9", "FACT,BYMONTH,M9")]
		[TestCase("FACT and BYMONTH and M8", "FACT,BYMONTH,M8")]
		[TestCase("FACT and BYMONTH and M7", "FACT,BYMONTH,M7")]
		[TestCase("FACT and BYMONTH and M6", "FACT,BYMONTH,M6")]
		[TestCase("FACT and BYMONTH and M5", "FACT,BYMONTH,M5")]
		[TestCase("FACT and BYMONTH and M4", "FACT,BYMONTH,M4")]
		[TestCase("FACT and BYMONTH and M3", "FACT,BYMONTH,M3")]
		[TestCase("FACT and BYMONTH and M2", "FACT,BYMONTH,M2")]
		[TestCase("FACT and BYMONTH and M1", "FACT,BYMONTH,M1")]
		[TestCase("OZHID and Y1", "OZHID,Y1")]
		[TestCase(" OZHID and OTKL and Y1 and OTKLABS ", "OZHID,OTKL,Y1,OTKLABS")]
		[TestCase("СНГ and OTKL", "СНГ,OTKL")]
		[TestCase("FACT and Y12", "FACT,Y12")]
		[TestCase("FACT and Y11", "FACT,Y11")]
		[TestCase("PRED and FACT and M1 ", "PRED,FACT,M1")]
		[TestCase("PLAN and OPERPLAN", "PLAN,OPERPLAN")]
		[TestCase("PLAN and FACT and OTKL and OPERPLAN", "PLAN,FACT,OTKL,OPERPLAN")]
		[TestCase("PLAN and FACT and OTKL", "PLAN,FACT,OTKL")]
		[TestCase("PLAN and FACT and OTKL and not OPERPLAN", "PLAN,FACT,OTKL,OPERPLAN")]
		[TestCase("OTKL and PREDYEAR", "OTKL,PREDYEAR")]
		[TestCase("Y12 and FACT", "Y12,FACT")]
		[TestCase("Y11 and FACT", "Y11,FACT")]
		[TestCase("Y10 and FACT", "Y10,FACT")]
		[TestCase("Y9 and FACT", "Y9,FACT")]
		[TestCase("Y8 and FACT", "Y8,FACT")]
		[TestCase("Y7 and FACT", "Y7,FACT")]
		[TestCase("Y6 and FACT", "Y6,FACT")]
		[TestCase("Y5 and FACT", "Y5,FACT")]
		[TestCase("Y4 and FACT", "Y4,FACT")]
		[TestCase("Y3 and FACT", "Y3,FACT")]
		[TestCase("Y2 and FACT", "Y2,FACT")]
		[TestCase("PLANPRED and Y1", "PLANPRED,Y1")]
		[TestCase("OZHID or FACT ", "OZHID,FACT")]
		[TestCase("PLAN and OTKL and PLANPRED", "PLAN,OTKL,PLANPRED")]
		[TestCase("PLAN and OTKL and OZHID and Y1", "PLAN,OTKL,OZHID,Y1")]
		[TestCase("PLAN and OTKL and FACT and Y1", "PLAN,OTKL,FACT,Y1")]
		[TestCase("OZHID and Y1 ", "OZHID,Y1")]
		[TestCase("PLAN and KOL and OSTN and BYMONTH", "PLAN,KOL,OSTN,BYMONTH")]
		[TestCase("PLAN and CENA and OSTN and BYMONTH", "PLAN,CENA,OSTN,BYMONTH")]
		[TestCase("PLAN and SUMMA and OSTN and BYMONTH", "PLAN,SUMMA,OSTN,BYMONTH")]
		[TestCase("PLAN and KOL and PRIHOD and BYMONTH", "PLAN,KOL,PRIHOD,BYMONTH")]
		[TestCase("PLAN and CENA and PRIHOD and BYMONTH", "PLAN,CENA,PRIHOD,BYMONTH")]
		[TestCase("PLAN and SUMMA and PRIHOD and BYMONTH", "PLAN,SUMMA,PRIHOD,BYMONTH")]
		[TestCase("PLAN and KOL and RASHOD and BYMONTH", "PLAN,KOL,RASHOD,BYMONTH")]
		[TestCase("PLAN and CENA and RASHOD and BYMONTH", "PLAN,CENA,RASHOD,BYMONTH")]
		[TestCase("PLAN and SUMMA and RASHOD and BYMONTH", "PLAN,SUMMA,RASHOD,BYMONTH")]
		[TestCase("PLAN and KOL and OSTK and BYMONTH", "PLAN,KOL,OSTK,BYMONTH")]
		[TestCase("PLAN and CENA and OSTK and BYMONTH", "PLAN,CENA,OSTK,BYMONTH")]
		[TestCase("PLAN and SUMMA and OSTK and BYMONTH", "PLAN,SUMMA,OSTK,BYMONTH")]
		[TestCase("PLAN and FACT and KOL and OSTN and BYMONTH and OTKL", "PLAN,FACT,KOL,OSTN,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and CENA and OSTN and BYMONTH and OTKL", "PLAN,FACT,CENA,OSTN,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and OSTN and BYMONTH and OTKL", "PLAN,FACT,SUMMA,OSTN,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and KOL and RASHOD and BYMONTH and OTKL", "PLAN,FACT,KOL,RASHOD,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and CENA and RASHOD and BYMONTH and OTKL", "PLAN,FACT,CENA,RASHOD,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and KOL and OSTK and BYMONTH and OTKL", "PLAN,FACT,KOL,OSTK,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and CENA and OSTK and BYMONTH and OTKL", "PLAN,FACT,CENA,OSTK,BYMONTH,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and OSTK and BYMONTH and OTKL", "PLAN,FACT,SUMMA,OSTK,BYMONTH,OTKL")]
		[TestCase("PLAN and KOL and OSTN and СНГ", "PLAN,KOL,OSTN,СНГ")]
		[TestCase("PLAN and CENA and OSTN and СНГ", "PLAN,CENA,OSTN,СНГ")]
		[TestCase("PLAN and SUMMA and OSTN and СНГ", "PLAN,SUMMA,OSTN,СНГ")]
		[TestCase("PLAN and KOL and PRIHOD and СНГ", "PLAN,KOL,PRIHOD,СНГ")]
		[TestCase("PLAN and CENA and PRIHOD and СНГ", "PLAN,CENA,PRIHOD,СНГ")]
		[TestCase("PLAN and SUMMA and PRIHOD and СНГ", "PLAN,SUMMA,PRIHOD,СНГ")]
		[TestCase("PLAN and KOL and RASHOD and СНГ", "PLAN,KOL,RASHOD,СНГ")]
		[TestCase("PLAN and SUMMA and RASHOD and СНГ", "PLAN,SUMMA,RASHOD,СНГ")]
		[TestCase("PLAN and KOL and OSTK and СНГ", "PLAN,KOL,OSTK,СНГ")]
		[TestCase("PLAN and CENA and OSTK and СНГ", "PLAN,CENA,OSTK,СНГ")]
		[TestCase("PLAN and SUMMA and OSTK and СНГ", "PLAN,SUMMA,OSTK,СНГ")]
		[TestCase("PLAN and FACT and KOL and OSTN and СНГ and OTKL", "PLAN,FACT,KOL,OSTN,СНГ,OTKL")]
		[TestCase("PLAN and FACT and CENA and OSTN and СНГ and OTKL", "PLAN,FACT,CENA,OSTN,СНГ,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and OSTN and СНГ and OTKL", "PLAN,FACT,SUMMA,OSTN,СНГ,OTKL")]
		[TestCase("PLAN and FACT and KOL and PRIHOD and СНГ and OTKL", "PLAN,FACT,KOL,PRIHOD,СНГ,OTKL")]
		[TestCase("PLAN and FACT and CENA and PRIHOD and СНГ and OTKL", "PLAN,FACT,CENA,PRIHOD,СНГ,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and PRIHOD and СНГ and OTKL", "PLAN,FACT,SUMMA,PRIHOD,СНГ,OTKL")]
		[TestCase("PLAN and FACT and KOL and RASHOD and СНГ and OTKL", "PLAN,FACT,KOL,RASHOD,СНГ,OTKL")]
		[TestCase("PLAN and FACT and CENA and RASHOD and СНГ and OTKL", "PLAN,FACT,CENA,RASHOD,СНГ,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and RASHOD and СНГ and OTKL", "PLAN,FACT,SUMMA,RASHOD,СНГ,OTKL")]
		[TestCase("PLAN and FACT and KOL and OSTK and СНГ and OTKL", "PLAN,FACT,KOL,OSTK,СНГ,OTKL")]
		[TestCase("PLAN and FACT and CENA and OSTK and СНГ and OTKL", "PLAN,FACT,CENA,OSTK,СНГ,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and OSTK and СНГ and OTKL", "PLAN,FACT,SUMMA,OSTK,СНГ,OTKL")]
		[TestCase("KOL and OSTN", "KOL,OSTN")]
		[TestCase("CENA and OSTN", "CENA,OSTN")]
		[TestCase("SUMMA and OSTN", "SUMMA,OSTN")]
		[TestCase("KOL and PRIHOD", "KOL,PRIHOD")]
		[TestCase("CENA and PRIHOD", "CENA,PRIHOD")]
		[TestCase("SUMMA and PRIHOD", "SUMMA,PRIHOD")]
		[TestCase("KOL and RASHOD", "KOL,RASHOD")]
		[TestCase("CENA and RASHOD", "CENA,RASHOD")]
		[TestCase("SUMMA and RASHOD", "SUMMA,RASHOD")]
		[TestCase("KOL and OSTK", "KOL,OSTK")]
		[TestCase("CENA and OSTK", "CENA,OSTK")]
		[TestCase("SUMMA and OSTK", "SUMMA,OSTK")]
		[TestCase("PLAN and KOL and OSTN", "PLAN,KOL,OSTN")]
		[TestCase("PLAN and KOL and OSTK", "PLAN,KOL,OSTK")]
		[TestCase("FACT and OSTN and BYMONTH", "FACT,OSTN,BYMONTH")]
		[TestCase("FACT and PRIHOD and BYMONTH", "FACT,PRIHOD,BYMONTH")]
		[TestCase("FACT and RASHOD and BYMONTH", "FACT,RASHOD,BYMONTH")]
		[TestCase("FACT and OSTK and BYMONTH", "FACT,OSTK,BYMONTH")]
		[TestCase("OSTN and BYMONTH", "OSTN,BYMONTH")]
		[TestCase("PLAN and FACT and OTKL and PRIHOD and BYMONTH", "PLAN,FACT,OTKL,PRIHOD,BYMONTH")]
		[TestCase("PLAN and FACT and OTKL and RASHOD and BYMONTH", "PLAN,FACT,OTKL,RASHOD,BYMONTH")]
		[TestCase("FACT and OSTN and СНГ", "FACT,OSTN,СНГ")]
		[TestCase("FACT and PRIHOD and СНГ", "FACT,PRIHOD,СНГ")]
		[TestCase("FACT and RASHOD and СНГ", "FACT,RASHOD,СНГ")]
		[TestCase("OSTN and СНГ", "OSTN,СНГ")]
		[TestCase("PRIHOD and СНГ", "PRIHOD,СНГ")]
		[TestCase("RASHOD and СНГ", "RASHOD,СНГ")]
		[TestCase("FACT and OSTK and СНГ", "FACT,OSTK,СНГ")]
		[TestCase("PLAN and FACT and OTKL and PRIHOD and СНГ", "PLAN,FACT,OTKL,PRIHOD,СНГ")]
		[TestCase("PLAN and FACT and OTKL and RASHOD and СНГ", "PLAN,FACT,OTKL,RASHOD,СНГ")]
		[TestCase("FACT and KOL and OSTN", "FACT,KOL,OSTN")]
		[TestCase("FACT and CENA and OSTN", "FACT,CENA,OSTN")]
		[TestCase("FACT and SUMMA and OSTN", "FACT,SUMMA,OSTN")]
		[TestCase("FACT and KOL and PRIHOD", "FACT,KOL,PRIHOD")]
		[TestCase("FACT and CENA and PRIHOD", "FACT,CENA,PRIHOD")]
		[TestCase("FACT and SUMMA and PRIHOD", "FACT,SUMMA,PRIHOD")]
		[TestCase("PLAN and PRIHOD ", "PLAN,PRIHOD")]
		[TestCase("FACT and PRIHOD", "FACT,PRIHOD")]
		[TestCase("PLAN and FACT and KOL and PRIHOD and OTKL", "PLAN,FACT,KOL,PRIHOD,OTKL")]
		[TestCase("PLAN and FACT and CENA and PRIHOD and OTKL", "PLAN,FACT,CENA,PRIHOD,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and PRIHOD and OTKL", "PLAN,FACT,SUMMA,PRIHOD,OTKL")]
		[TestCase("FACT and KOL and RASHOD", "FACT,KOL,RASHOD")]
		[TestCase("FACT and CENA and RASHOD", "FACT,CENA,RASHOD")]
		[TestCase("FACT and SUMMA and RASHOD", "FACT,SUMMA,RASHOD")]
		[TestCase("PLAN and RASHOD ", "PLAN,RASHOD")]
		[TestCase("FACT and RASHOD", "FACT,RASHOD")]
		[TestCase("PLAN and FACT and KOL and RASHOD and OTKL", "PLAN,FACT,KOL,RASHOD,OTKL")]
		[TestCase("PLAN and FACT and CENA and RASHOD and OTKL", "PLAN,FACT,CENA,RASHOD,OTKL")]
		[TestCase("PLAN and FACT and SUMMA and RASHOD and OTKL", "PLAN,FACT,SUMMA,RASHOD,OTKL")]
		[TestCase("PLAN and SUMMA and OSTK", "PLAN,SUMMA,OSTK")]
		[TestCase("FACT and KOL and OSTK", "FACT,KOL,OSTK")]
		[TestCase("FACT and CENA and OSTK", "FACT,CENA,OSTK")]
		[TestCase("FACT and SUMMA and OSTK", "FACT,SUMMA,OSTK")]
		[TestCase("Y2 and FACT and KOL and PRIHOD ", "Y2,FACT,KOL,PRIHOD")]
		[TestCase("Y2 and FACT and CENA and PRIHOD ", "Y2,FACT,CENA,PRIHOD")]
		[TestCase("Y2 and FACT and SUMMA and PRIHOD", "Y2,FACT,SUMMA,PRIHOD")]
		[TestCase("Y2 and FACT and KOL and RASHOD ", "Y2,FACT,KOL,RASHOD")]
		[TestCase("Y2 and FACT and CENA and RASHOD ", "Y2,FACT,CENA,RASHOD")]
		[TestCase("Y2 and FACT and SUMMA and RASHOD ", "Y2,FACT,SUMMA,RASHOD")]
		[TestCase("Y1 and PLAN and KOL and PRIHOD ", "Y1,PLAN,KOL,PRIHOD")]
		[TestCase("Y1 and PLAN and CENA and PRIHOD ", "Y1,PLAN,CENA,PRIHOD")]
		[TestCase("Y1 and PLAN and KOL and RASHOD ", "Y1,PLAN,KOL,RASHOD")]
		[TestCase("Y1 and PLAN and CENA and RASHOD ", "Y1,PLAN,CENA,RASHOD")]
		[TestCase("Y1 and PLAN and SUMMA and RASHOD ", "Y1,PLAN,SUMMA,RASHOD")]
		[TestCase("Y1 and FACT and KOL and PRIHOD ", "Y1,FACT,KOL,PRIHOD")]
		[TestCase("Y1 and FACT and CENA and PRIHOD ", "Y1,FACT,CENA,PRIHOD")]
		[TestCase("Y1 and FACT and KOL and RASHOD ", "Y1,FACT,KOL,RASHOD")]
		[TestCase("Y1 and FACT and CENA and RASHOD ", "Y1,FACT,CENA,RASHOD")]
		[TestCase("Y1 and FACT and SUMMA and RASHOD ", "Y1,FACT,SUMMA,RASHOD")]
		[TestCase("OTKL and PLAN and Y1 and FACT and KOL and PRIHOD ", "OTKL,PLAN,Y1,FACT,KOL,PRIHOD")]
		[TestCase("OTKL and PLAN and Y1 and FACT and CENA and PRIHOD ", "OTKL,PLAN,Y1,FACT,CENA,PRIHOD")]
		[TestCase("OTKL and PLAN and Y1 and FACT and SUMMA and PRIHOD ", "OTKL,PLAN,Y1,FACT,SUMMA,PRIHOD")]
		[TestCase("OTKL and Y1 and PLAN and FACT and SUMMA and PRIHOD ", "OTKL,Y1,PLAN,FACT,SUMMA,PRIHOD")]
		[TestCase("OTKL and PLAN and Y1 and FACT and KOL and RASHOD ", "OTKL,PLAN,Y1,FACT,KOL,RASHOD")]
		[TestCase("OTKL and PLAN and Y1 and FACT and CENA and RASHOD ", "OTKL,PLAN,Y1,FACT,CENA,RASHOD")]
		[TestCase("OTKL and PLAN and Y1 and FACT and SUMMA and RASHOD ", "OTKL,PLAN,Y1,FACT,SUMMA,RASHOD")]
		[TestCase("OTKL and Y1 and PLAN and FACT and SUMMA and RASHOD ", "OTKL,Y1,PLAN,FACT,SUMMA,RASHOD")]
		[TestCase("OTKL and PLAN and Y1 and KOL and PRIHOD ", "OTKL,PLAN,Y1,KOL,PRIHOD")]
		[TestCase("OTKL and PLAN and Y1 and CENA and PRIHOD ", "OTKL,PLAN,Y1,CENA,PRIHOD")]
		[TestCase("OTKL and Y1 and PLAN and SUMMA and PRIHOD ", "OTKL,Y1,PLAN,SUMMA,PRIHOD")]
		[TestCase("OTKL and PLAN and Y1 and KOL and RASHOD ", "OTKL,PLAN,Y1,KOL,RASHOD")]
		[TestCase("OTKL and PLAN and Y1 and CENA and RASHOD ", "OTKL,PLAN,Y1,CENA,RASHOD")]
		[TestCase("OTKL and Y1 and PLAN and SUMMA and RASHOD ", "OTKL,Y1,PLAN,SUMMA,RASHOD")]
		[TestCase("FACT and OSTN ", "FACT,OSTN")]
		[TestCase("FACT and PRIHOD ", "FACT,PRIHOD")]
		[TestCase("FACT and RASHOD ", "FACT,RASHOD")]
		[TestCase("FACT and OSTK ", "FACT,OSTK")]
		[TestCase("FACT and BYMONTH and KOL", "FACT,BYMONTH,KOL")]
		[TestCase("FACT and BYMONTH and VSEGO and CENA", "FACT,BYMONTH,VSEGO,CENA")]
		[TestCase("FACT and BYMONTH and VSEGO and SS", "FACT,BYMONTH,VSEGO,SS")]
		[TestCase("FACT and BYMONTH and VSEGO and UR", "FACT,BYMONTH,VSEGO,UR")]
		[TestCase("FACT and BYMONTH and VSEGO and KR", "FACT,BYMONTH,VSEGO,KR")]
		[TestCase("FACT and BYMONTH and VSEGO and PRIB", "FACT,BYMONTH,VSEGO,PRIB")]
		[TestCase("FACT and BYMONTH and VSEGO and PROC", "FACT,BYMONTH,VSEGO,PROC")]
		[TestCase("FACT and СНГ and KOL", "FACT,СНГ,KOL")]
		[TestCase("FACT and СНГ and VSEGO and CENA", "FACT,СНГ,VSEGO,CENA")]
		[TestCase("FACT and СНГ and VSEGO and SS", "FACT,СНГ,VSEGO,SS")]
		[TestCase("FACT and СНГ and VSEGO and UR", "FACT,СНГ,VSEGO,UR")]
		[TestCase("FACT and СНГ and VSEGO and KR", "FACT,СНГ,VSEGO,KR")]
		[TestCase("FACT and СНГ and VSEGO and PRIB", "FACT,СНГ,VSEGO,PRIB")]
		[TestCase("FACT and СНГ and VSEGO and PROC", "FACT,СНГ,VSEGO,PROC")]
		[TestCase("CENA and ED ", "CENA,ED")]
		[TestCase("SS and ED ", "SS,ED")]
		[TestCase("UR and ED ", "UR,ED")]
		[TestCase("KR and ED ", "KR,ED")]
		[TestCase("ZATR and ED ", "ZATR,ED")]
		[TestCase("PRIB and ED ", "PRIB,ED")]
		[TestCase("PROC and ED ", "PROC,ED")]
		[TestCase("CENA and VSEGO", "CENA,VSEGO")]
		[TestCase("SS and VSEGO", "SS,VSEGO")]
		[TestCase("UR and VSEGO", "UR,VSEGO")]
		[TestCase("KR and VSEGO", "KR,VSEGO")]
		[TestCase("ZATR and VSEGO", "ZATR,VSEGO")]
		[TestCase("PRIB and VSEGO", "PRIB,VSEGO")]
		[TestCase("PROC and VSEGO", "PROC,VSEGO")]
		[TestCase("FACT and BYMONTH and ED and CENA", "FACT,BYMONTH,ED,CENA")]
		[TestCase("FACT and BYMONTH and ED and SS", "FACT,BYMONTH,ED,SS")]
		[TestCase("FACT and BYMONTH and ED and UR", "FACT,BYMONTH,ED,UR")]
		[TestCase("FACT and BYMONTH and ED and KR", "FACT,BYMONTH,ED,KR")]
		[TestCase("FACT and BYMONTH and ED and PRIB", "FACT,BYMONTH,ED,PRIB")]
		[TestCase("FACT and BYMONTH and ED and PROC", "FACT,BYMONTH,ED,PROC")]
		[TestCase("FACT and СНГ and ED and CENA", "FACT,СНГ,ED,CENA")]
		[TestCase("FACT and СНГ and ED and SS", "FACT,СНГ,ED,SS")]
		[TestCase("FACT and СНГ and ED and UR", "FACT,СНГ,ED,UR")]
		[TestCase("FACT and СНГ and ED and KR", "FACT,СНГ,ED,KR")]
		[TestCase("FACT and СНГ and ED and PRIB", "FACT,СНГ,ED,PRIB")]
		[TestCase("FACT and СНГ and ED and PROC", "FACT,СНГ,ED,PROC")]
		[TestCase("ED and CENA", "ED,CENA")]
		[TestCase("ED and PSS", "ED,PSS")]
		[TestCase("ED and SS", "ED,SS")]
		[TestCase("ED and UR", "ED,UR")]
		[TestCase("ED and KR", "ED,KR")]
		[TestCase("ED and PRIB", "ED,PRIB")]
		[TestCase("ED and PROC", "ED,PROC")]
		[TestCase("VSEGO and CENA", "VSEGO,CENA")]
		[TestCase("VSEGO and PSS", "VSEGO,PSS")]
		[TestCase("VSEGO and SS", "VSEGO,SS")]
		[TestCase("VSEGO and UR", "VSEGO,UR")]
		[TestCase("VSEGO and KR", "VSEGO,KR")]
		[TestCase("VSEGO and PRIB", "VSEGO,PRIB")]
		[TestCase("VSEGO and PROC", "VSEGO,PROC")]
		[TestCase("KOL and not VSEGO", "KOL,VSEGO")]
		[TestCase("CENA and ED", "CENA,ED")]
		[TestCase("PSS and ED", "PSS,ED")]
		[TestCase("SS and ED", "SS,ED")]
		[TestCase("UR and ED", "UR,ED")]
		[TestCase("KR and ED", "KR,ED")]
		[TestCase("PRIB and ED", "PRIB,ED")]
		[TestCase("PROC and ED", "PROC,ED")]
		[TestCase("ZATR and ED", "ZATR,ED")]
		[TestCase("PRIBPROC and ED", "PRIBPROC,ED")]
		[TestCase("KOL and VSEGO", "KOL,VSEGO")]
		[TestCase("PSS and VSEGO", "PSS,VSEGO")]
		[TestCase("PRIBPROC and VSEGO", "PRIBPROC,VSEGO")]
		[TestCase("OZHID and OZHID", "OZHID")]
		[TestCase("USETPFP and PLAN and not USEKORRTPFP", "USETPFP,PLAN,USEKORRTPFP")]
		[TestCase("USETPFP and PLAN and USEKORRTPFP ", "USETPFP,PLAN,USEKORRTPFP")]
		[TestCase("USETPFP and PLAN and not USEKORRTPFP and SHOWKORRTPFP", "USETPFP,PLAN,USEKORRTPFP,SHOWKORRTPFP")]
		[TestCase("USETPFP and PLAN and USEKORRTPFP and SHOWKORRTPFP", "USETPFP,PLAN,USEKORRTPFP,SHOWKORRTPFP")]
		[TestCase("PLAN and SHOWKORRTPFP", "PLAN,SHOWKORRTPFP")]
		[TestCase(" PLAN", "PLAN")]
		[TestCase(" PLAN and SHOWKORRTPFP", "PLAN,SHOWKORRTPFP")]
		[TestCase(" PLAN and USEKORRTPFP", "PLAN,USEKORRTPFP")]
		[TestCase("PREDFACT and USETPFP and PLAN and not USEKORRTPFP", "PREDFACT,USETPFP,PLAN,USEKORRTPFP")]
		[TestCase("PREDFACT and USETPFP and PLAN and USEKORRTPFP ", "PREDFACT,USETPFP,PLAN,USEKORRTPFP")]
		[TestCase("PREDFACT and USETPFP and PLAN and not USEKORRTPFP and SHOWKORRTPFP", "PREDFACT,USETPFP,PLAN,USEKORRTPFP,SHOWKORRTPFP")]
		[TestCase("PREDFACT and USETPFP and PLAN and USEKORRTPFP and SHOWKORRTPFP", "PREDFACT,USETPFP,PLAN,USEKORRTPFP,SHOWKORRTPFP")]
		[TestCase(" SNG and PLAN", "SNG,PLAN")]
		[TestCase("PREDFACT and FACT", "PREDFACT,FACT")]
		[TestCase("OTKL and PLAN and PREDFACT and OTKLABS and not USEKORRTPFP ", "OTKL,PLAN,PREDFACT,OTKLABS,USEKORRTPFP")]
		[TestCase("OTKL and PLAN and PREDFACT and OTKLOTN and not USEKORRTPFP ", "OTKL,PLAN,PREDFACT,OTKLOTN,USEKORRTPFP")]
		[TestCase("OTKL and PLAN and PREDFACT and OTKLABS and USEKORRTPFP ", "OTKL,PLAN,PREDFACT,OTKLABS,USEKORRTPFP")]
		[TestCase("OTKL and PLAN and PREDFACT and OTKLOTN and USEKORRTPFP ", "OTKL,PLAN,PREDFACT,OTKLOTN,USEKORRTPFP")]
		[TestCase("PLAN and K1", "PLAN,K1")]
		[TestCase("PLAN and K2", "PLAN,K2")]
		[TestCase("PLAN and K3", "PLAN,K3")]
		[TestCase("PLAN and K4", "PLAN,K4")]
		[TestCase("OTKL and PREDFACT and OTKLABS ", "OTKL,PREDFACT,OTKLABS")]
		[TestCase("OTKL and PLAN and OTKLABS", "OTKL,PLAN,OTKLABS")]
		[TestCase("OTKL and PLAN and OTKLABS and SNG ", "OTKL,PLAN,OTKLABS,SNG")]
		[TestCase("OTKL and PREDFACT and OTKLOTN ", "OTKL,PREDFACT,OTKLOTN")]
		[TestCase("OTKL and PLAN and OTKLOTN and SNG", "OTKL,PLAN,OTKLOTN,SNG")]
		[TestCase("SUMMAYEAR and Y12", "SUMMAYEAR,Y12")]
		[TestCase("SUMMAYEAR and Y11 and not Y12", "SUMMAYEAR,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y10 and not Y11 and not Y12", "SUMMAYEAR,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y9,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y8 and not Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y8,Y9,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y7 and not Y8 and not Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y7,Y8,Y9,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y6 and not Y7 and not Y8 and not Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y6,Y7,Y8,Y9,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y5 and not Y6 and not Y7 and not Y8 and not Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y5,Y6,Y7,Y8,Y9,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y4 and not Y5 and not Y6 and not Y7 and not Y8 and not Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y4,Y5,Y6,Y7,Y8,Y9,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y3 and not Y4 and not Y5 and not Y6 and not Y7 and not Y8 and not Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10,Y11,Y12")]
		[TestCase("SUMMAYEAR and Y2 and not Y3 and not Y4 and not Y5 and not Y6 and not Y7 and not Y8 and not Y9 and not Y10 and not Y11 and not Y12", "SUMMAYEAR,Y2,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10,Y11,Y12")]
		[TestCase("PLANPRED and PLAN and SHOWKORRTPFP", "PLANPRED,PLAN,SHOWKORRTPFP")]
		[TestCase("(not ONLYONEPERIOD) and Погодам and yc5", "ONLYONEPERIOD,Погодам,yc5")]
		[TestCase("(not ONLYONEPERIOD) and Погодам and yc4", "ONLYONEPERIOD,Погодам,yc4")]
		[TestCase("(not ONLYONEPERIOD) and Погодам and yc3", "ONLYONEPERIOD,Погодам,yc3")]
		[TestCase("(not ONLYONEPERIOD) and Погодам and yc2", "ONLYONEPERIOD,Погодам,yc2")]
		[TestCase("(not ONLYONEPERIOD) and Погодам", "ONLYONEPERIOD,Погодам")]
		[TestCase("(not ONLYONEPERIOD) and МПогодам and yc5", "ONLYONEPERIOD,МПогодам,yc5")]
		[TestCase("(not ONLYONEPERIOD) and МПогодам and yc4", "ONLYONEPERIOD,МПогодам,yc4")]
		[TestCase("(not ONLYONEPERIOD) and МПогодам and yc3", "ONLYONEPERIOD,МПогодам,yc3")]
		[TestCase("(not ONLYONEPERIOD) and МПогодам and yc2", "ONLYONEPERIOD,МПогодам,yc2")]
		[TestCase("(not ONLYONEPERIOD) and МПогодам", "ONLYONEPERIOD,МПогодам")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv1 ) and yc5", "ONLYONEPERIOD,Попериодам,kv1,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv2 ) and yc5", "ONLYONEPERIOD,Попериодам,kv2,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv3 ) and yc5", "ONLYONEPERIOD,Попериодам,kv3,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv4 ) and yc5", "ONLYONEPERIOD,Попериодам,kv4,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv1 ) and yc4", "ONLYONEPERIOD,Попериодам,kv1,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv2 ) and yc4", "ONLYONEPERIOD,Попериодам,kv2,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv3 ) and yc4", "ONLYONEPERIOD,Попериодам,kv3,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv4 ) and yc4", "ONLYONEPERIOD,Попериодам,kv4,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv1 ) and yc3", "ONLYONEPERIOD,Попериодам,kv1,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv2 ) and yc3", "ONLYONEPERIOD,Попериодам,kv2,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv3 ) and yc3", "ONLYONEPERIOD,Попериодам,kv3,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv4 ) and yc3", "ONLYONEPERIOD,Попериодам,kv4,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv1 ) and yc2", "ONLYONEPERIOD,Попериодам,kv1,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv2 ) and yc2", "ONLYONEPERIOD,Попериодам,kv2,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv3 ) and yc2", "ONLYONEPERIOD,Попериодам,kv3,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv4 ) and yc2", "ONLYONEPERIOD,Попериодам,kv4,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv1 ) and yc1", "ONLYONEPERIOD,Попериодам,kv1,yc1")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv2 ) and yc1", "ONLYONEPERIOD,Попериодам,kv2,yc1")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv3 ) and yc1", "ONLYONEPERIOD,Попериодам,kv3,yc1")]
		[TestCase("(not ONLYONEPERIOD) and (Попериодам and kv4 ) and yc1", "ONLYONEPERIOD,Попериодам,kv4,yc1")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv1 ) and yc5", "ONLYONEPERIOD,Покварталам,kv1,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv2 ) and yc5", "ONLYONEPERIOD,Покварталам,kv2,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv3 ) and yc5", "ONLYONEPERIOD,Покварталам,kv3,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv4 ) and yc5", "ONLYONEPERIOD,Покварталам,kv4,yc5")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv1 ) and yc4", "ONLYONEPERIOD,Покварталам,kv1,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv2 ) and yc4", "ONLYONEPERIOD,Покварталам,kv2,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv3 ) and yc4", "ONLYONEPERIOD,Покварталам,kv3,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv4 ) and yc4", "ONLYONEPERIOD,Покварталам,kv4,yc4")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv1 ) and yc3", "ONLYONEPERIOD,Покварталам,kv1,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv2 ) and yc3", "ONLYONEPERIOD,Покварталам,kv2,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv3 ) and yc3", "ONLYONEPERIOD,Покварталам,kv3,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv4 ) and yc3", "ONLYONEPERIOD,Покварталам,kv4,yc3")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv1 ) and yc2", "ONLYONEPERIOD,Покварталам,kv1,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv2 ) and yc2", "ONLYONEPERIOD,Покварталам,kv2,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv3 ) and yc2", "ONLYONEPERIOD,Покварталам,kv3,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv4 ) and yc2", "ONLYONEPERIOD,Покварталам,kv4,yc2")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv1 ) and yc1", "ONLYONEPERIOD,Покварталам,kv1,yc1")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv2 ) and yc1", "ONLYONEPERIOD,Покварталам,kv2,yc1")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv3 ) and yc1", "ONLYONEPERIOD,Покварталам,kv3,yc1")]
		[TestCase("(not ONLYONEPERIOD) and (Покварталам and kv4 ) and yc1", "ONLYONEPERIOD,Покварталам,kv4,yc1")]
		[TestCase("(not ONLYONEPERIOD) and  Помесяцам and yc5", "ONLYONEPERIOD,Помесяцам,yc5")]
		[TestCase("(not ONLYONEPERIOD) and  Помесяцам and yc4", "ONLYONEPERIOD,Помесяцам,yc4")]
		[TestCase("(not ONLYONEPERIOD) and  Помесяцам and yc3", "ONLYONEPERIOD,Помесяцам,yc3")]
		[TestCase("(not ONLYONEPERIOD) and  Помесяцам and yc2", "ONLYONEPERIOD,Помесяцам,yc2")]
		[TestCase("(not ONLYONEPERIOD) and  Помесяцам and yc1", "ONLYONEPERIOD,Помесяцам,yc1")]
		[TestCase("(not ONLYONEPERIOD) and Помесяцам and Помесяцамвсего", "ONLYONEPERIOD,Помесяцам,Помесяцамвсего")]
		public void OldAndNewBehaviorEqualityTest(string formula, string termlist) {
			var terms = termlist.Split(',');
			var setgenerator = new ConditionSetGenerator(terms);
			var oldmatcher = new OldConditionMatcherImplementation();
			var newmatcher = new NewConditionMatcherImplementation();

			foreach (var conditionSet in setgenerator.GenerateConditionSets()) {
				var conditions = conditionSet as string[] ?? conditionSet.ToArray();
				var oldresult = oldmatcher.Match(formula, conditions);
				var newresult = newmatcher.Match(formula, conditions);
				Assert.AreEqual(oldresult,newresult,string.Join(",",conditions));
			}
		}
	}
}